theme: jekyll-theme-minimal
logo: https://raw.githubusercontent.com/sumedhkhodke/sumedhkhodke.github.io/main/portrait.jpg
title: Sumedh Khodke
baseurl: ""
url: "https://sumedhkhodke.github.io"
markdown: kramdown